### ISSUE TITLE
LrEntity with no IDs - deobfuscate exceptions

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#155]
Selecting of LrEntity with no id results in a confusing stack. AttributeEncoderFactory should  check for this condition and throw something more user-friendly. 

```

java.util.NoSuchElementException: null
	at java.util.ArrayList$Itr.next(ArrayList.java:839) ~[na:1.8.0]
	at com.nhl.link.rest.runtime.encoder.AttributeEncoderFactory.buildIdProperty(AttributeEncoderFactory.java:119) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.encoder.AttributeEncoderFactory.getIdProperty(AttributeEncoderFactory.java:66) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.encoder.EncoderService.entityEncoder(EncoderService.java:153) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.encoder.EncoderService.collectionElementEncoder(EncoderService.java:103) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.encoder.EncoderService.dataEncoder(EncoderService.java:74) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.processor.select.ApplySelectServerParamsStage.doExecute(ApplySelectServerParamsStage.java:52) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.processor.select.ApplySelectServerParamsStage.doExecute(ApplySelectServerParamsStage.java:17) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.processor.BaseLinearProcessingStage.execute(BaseLinearProcessingStage.java:20) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:18) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:22) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:22) ~[link-rest-1.21.jar:na]
	at com.nhl.link.rest.runtime.DefaultSelectBuilder.select(DefaultSelectBuilder.java:196) ~[link-rest-1.21.jar:na]
```

**Comment by andrus** [comment]
superseded by #156
