### ISSUE TITLE
Sorting on a POJO property of a persistent object causes an exception

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#180]
Consider the entity below that mixes persistent and non-persistent properties:

```java
public class MyEntity extends _MyEntity {
   private String nonPersistent;

   @LrAttribute
   public String getNonPersistent() {
      return nonPersistent;
   }
}
```
Passing ```sort=nonPersistent``` in the URL would result in LR trying to use this property when generating SQL and in Cayenne translator exception:

```
INFO  [2016-06-01 11:45:34,228] media-rest-pool-3 o.a.c.l.CommonsJdbcEventLogger: *** error.
org.apache.cayenne.exp.ExpressionException: [v.4.0.M3 Feb 08 2016 16:38:05] Can't resolve path component: [MyEntity.nonPersistent].
	at org.apache.cayenne.map.PathComponentIterator.invalidPathException(PathComponentIterator.java:145)
	at org.apache.cayenne.map.PathComponentIterator.next(PathComponentIterator.java:133)
	at org.apache.cayenne.map.PathComponentIterator.next(PathComponentIterator.java:33)
	at org.apache.cayenne.access.translator.select.QueryAssemblerHelper.appendObjPath(QueryAssemblerHelper.java:136)
	at org.apache.cayenne.access.translator.select.OrderingTranslator.doAppendPart(OrderingTranslator.java:80)
	at org.apache.cayenne.access.translator.select.QueryAssemblerHelper.appendPart(QueryAssemblerHelper.java:78)
```

**Comment by atomashpolskiy** [comment]
After looking deeper into the problem, it turns out that the main problem is that sorting is pretty tightly bound to the Cayenne. More specifically, all sort attributes are stored in ResouceEntity in the form of Cayenne's `Ordering`s. Translation from the string sort spec to the Ordering is done by the `com.nhl.link.rest.runtime.parser.sort.SortWorker` with the help of `com.nhl.link.rest.runtime.parser.cache.EntityPathCache#getPathDescriptor(ASTObjPath)`. Here lies the problem -- for persistent attributes the sort spec is transformed by the PathDescriptor's underlying CayenneLrDbAttribute into an ASTDbPath form with a `db:` prefix. The reverse transformation is not always possible -- e.g. when `id` is translated into `db:entity_id`. It's also problematic to change `com.nhl.link.rest.runtime.parser.cache.PathCache#getPathDescriptor` method to accept more generic `ASTPath`. In the end all this probably means that we would have to separate processing of sort attributes that belong to different back-ends -- either explicitly by storing them in different properties of the ResourceEntity or implicitly by creating some `LrOrdering` interface that will abstract away the back-end specific details.
