### ISSUE TITLE
LinkRest 1.x to support Cayenne 4.0.M5

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#216]
I have a need for LR that supports Java 7, but also the upcoming Cayenne 4.0.M5. Noticed one binary incompatibility:

```
Caused by: java.lang.NoSuchMethodError: org.apache.cayenne.exp.parser.ASTEqual.<init>(Lorg/apache/cayenne/exp/parser/ASTPath;Ljava/lang/Object;)V
	at com.nhl.link.rest.runtime.cayenne.ByIdObjectMapper.match(ByIdObjectMapper.java:68)
	at com.nhl.link.rest.runtime.cayenne.ByIdObjectMapper.expressionForKey(ByIdObjectMapper.java:51)
	at com.nhl.link.rest.runtime.cayenne.processor.CayenneUpdateStage.itemsForKeys(CayenneUpdateStage.java:114)
	at com.nhl.link.rest.runtime.cayenne.processor.CayenneUpdateStage.sync(CayenneUpdateStage.java:42)
	at com.nhl.link.rest.runtime.cayenne.processor.BaseCayenneUpdateStage.doExecute(BaseCayenneUpdateStage.java:38)
	at com.nhl.link.rest.runtime.cayenne.processor.BaseCayenneUpdateStage.doExecute(BaseCayenneUpdateStage.java:30)
	at com.nhl.link.rest.processor.BaseLinearProcessingStage.execute(BaseLinearProcessingStage.java:20)
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:18)
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:22)
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:22)
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:22)
	at com.nhl.link.rest.processor.ChainProcessor.execute(ChainProcessor.java:22)
	at com.nhl.link.rest.runtime.DefaultUpdateBuilder.doSync(DefaultUpdateBuilder.java:215)
	at com.nhl.link.rest.runtime.DefaultUpdateBuilder.sync(DefaultUpdateBuilder.java:165)
```

**Comment by andrus** [comment]
This is kinda ready, pending official Cayenne M5 release that is to happen some time in March 2017
