### ISSUE TITLE
Dynamic relationships do not work with "mapBy" 

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#238]
Admittedly this is not a very common case. I am joining 2 Cayenne models in runtime, creating dynamic ObjRelationships. Such relationships work fine in "include" and other places, but do not work as "mapBy" keys. `GET_DynamicAttributesIT.testMapByRel()` demonstrates the issue, which is the use of bean property reader for mapBy-over-relationship instead of DataObject property reader:

```
Caused by: java.lang.IllegalArgumentException: Property 'e22' is not readable
	at org.apache.cayenne.reflect.BeanAccessor.<init>(BeanAccessor.java:92)
	at org.apache.cayenne.reflect.PropertyUtils.createSegmentAccessor(PropertyUtils.java:115)
	at org.apache.cayenne.reflect.PropertyUtils.getOrCreateSegmentAccessor(PropertyUtils.java:102)
	at org.apache.cayenne.reflect.PropertyUtils$PathAccessor.getValue(PropertyUtils.java:232)
	at org.apache.cayenne.reflect.PropertyUtils.getProperty(PropertyUtils.java:124)
	at com.nhl.link.rest.property.BeanPropertyReader.value(BeanPropertyReader.java:25)
	at com.nhl.link.rest.property.PropertyBuilder.read(PropertyBuilder.java:76)
	at com.nhl.link.rest.encoder.MapByEncoder.lambda$getPropertyReader$0(MapByEncoder.java:49)
	at com.nhl.link.rest.encoder.MapByEncoder.mapByValue(MapByEncoder.java:158)
```

**Comment by andrus** [comment]
@atomashpolskiy : it looks like LrEntity is not compiled properly by CayenneEntityCompiler. Dynamic attributes are recognized as persistent, while dynamic relationships are not.

**Comment by andrus** [comment]
Interestingly the problem (and [the fix](https://github.com/nhl/link-rest/commit/81d722cad598a179576a256a46f368792ff8a6d2#diff-024f067ef289159939cdea9947540c3a) ) are not related to the generic nature of the entity. Just that if the relationship is not generic, the result of the erroneous calculation was ignored.
