### ISSUE TITLE
POST: java.util.Date to Timestamp conversion

### ISSUE THREAD

**Issue by andrus** [nhl/link-rest#267]
cc: @atomashpolskiy 

Been testing LinkRest with Cayenne 4.1.M1 that features field-based objects and requires strict type conversion. Encountered this error in `POST_IT.testPost_DateTime` that was previously hidden by the generic nature of CayenneDataObject. Here LR is trying to set a `java.sql.Timestamp` field with a `java.util.Date` object. We won't see this error with Cayenne 4.0, but the stack should still point to the place where an explicit conversion is due.

```
    ...
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at com.nhl.link.rest.it.POST_IT.testPost_DateTime(POST_IT.java:95)Starter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: java.util.Date cannot be cast to java.sql.Timestamp
	at com.nhl.link.rest.it.fixture.cayenne.auto._E16.writePropertyDirectly(_E16.java:96)
	at org.apache.cayenne.BaseDataObject.writeProperty(BaseDataObject.java:220)
	at com.nhl.link.rest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.mergeChanges(CayenneUpdateDataStoreStage.java:178)
	at com.nhl.link.rest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.createSingle(CayenneUpdateDataStoreStage.java:134)
	at com.nhl.link.rest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.create(CayenneUpdateDataStoreStage.java:55)
	at com.nhl.link.rest.runtime.cayenne.processor.update.CayenneCreateStage.sync(CayenneCreateStage.java:19)
	at com.nhl.link.rest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.execute(CayenneUpdateDataStoreStage.java:43)
	at com.nhl.link.rest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.execute(CayenneUpdateDataStoreStage.java:33)
	at com.nhl.link.rest.processor.Processor.lambda$andThen$0(Processor.java:19)
	at com.nhl.link.rest.processor.Processor.lambda$andThen$0(Processor.java:17)
	at com.nhl.link.rest.runtime.DefaultUpdateBuilder.doSyncAndSelect(DefaultUpdateBuilder.java:236)
	at com.nhl.link.rest.runtime.DefaultUpdateBuilder.syncAndSelect(DefaultUpdateBuilder.java:208)
	at com.nhl.link.rest.it.POST_IT$Resource.createE16(POST_IT.java:433)
	
```

**Comment by andrus** [comment]
@atomashpolskiy Thanks for the quick fix. Can we write some tests for this as well?

**Comment by atomashpolskiy** [comment]
@andrus , added unit tests
