### ISSUE TITLE
Intermittent error in UtcDateConverterTest.testConverter_javaUtilDate test

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-rest#273]
Just caught a bizarre error during Maven build, that happened once again in a standalone Junit run from IDE and can't be reproduced anymore. Note the trailing whitespace after the _expected_ value.
```
java.lang.AssertionError: expected: java.util.Date<Tue Oct 17 15:05:44 MSK 2017> but was: java.util.Date<Tue Oct 17 15:05:44 MSK 2017>
Expected :java.util.Date<Tue Oct 17 15:05:44 MSK 2017> 
Actual   :java.util.Date<Tue Oct 17 15:05:44 MSK 2017>

at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.nhl.link.rest.parser.converter.UtcDateConverterTest.testConverter_javaUtilDate(UtcDateConverterTest.java:16)
```

**Comment by atomashpolskiy** [comment]
Oh, in fact during Maven build all 4 test cases failed:
```
Failed tests: 
  UtcDateConverterTest.testConverter_javaSqlDate:23 expected:<Tue Oct 17 15:03:49 MSK 2017> but was:<2017-10-17>
  UtcDateConverterTest.testConverter_javaSqlTime:30 expected:<Tue Oct 17 15:03:49 MSK 2017> but was:<15:03:49>
  UtcDateConverterTest.testConverter_javaSqlTimestamp:37 expected:<Tue Oct 17 15:03:49 MSK 2017> but was:<2017-10-17 15:03:49.83>
  UtcDateConverterTest.testConverter_javaUtilDate:16 expected: java.util.Date<Tue Oct 17 15:03:49 MSK 2017> but was: java.util.Date<Tue Oct 17 15:03:49 MSK 2017>
```

**Comment by atomashpolskiy** [comment]
Caught this one more time yesterday.

**Comment by atomashpolskiy** [comment]
While working on #275, I've noticed that we've been using the following string format in this test: `yyyy-MM-dd'T'HH:mm:ss.S` (via `java.text.SimpleDateFormat`), which apparently is not always compatible with Java 8 parsers, that are used on the server side. From now on, will use Java 8 formatter instead, hope that this will help eliminate the issue.

**Comment by atomashpolskiy** [comment]
To elaborate, here's a comparison of output of `SimpleDateFormat` and `DateTimeFormatter` for the same dates:

```java
long time = 1458995247001L; // fractional part is 1 millisecond
new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.S").format(new Date(time));
// => 2016-03-26 15:27:27.1
DateTimeFormatters.isoLocalDateTime().format(Instant.ofEpochMilli(time));
// => 2016-03-26T15:27:27.001

time = 1458995247100L; // fractional part is 100 milliseconds
new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.S").format(new Date(time));
// => 2016-03-26 15:27:27.100
DateTimeFormatters.isoLocalDateTime().format(Instant.ofEpochMilli(time));
// => 2016-03-26T15:27:27.1
```

Quite obviously, sometimes the results match, specifically when:
- the fractional part is absent
- or the number of milliseconds is between 101 and 999 and has no trailing zeros.
